### PR TITLE
[module] Fix build on Linux 6.4 (fixes #1075)

### LINKED ISSUE #1075: Error building DKMS module for kernel 6.4.0-rc1 kvmfr/0.0.8
On Arch Linux when upgrading the [mainline kernel](https://aur.archlinux.org/packages/linux-mainline) I saw the following error.  

```
Install DKMS modules
==> dkms install --no-depmod kvmfr/0.0.8 -k 6.4.0-rc1-1-mainline
Error! Bad return status for module build on kernel: 6.4.0-rc1-1-mainline (x86_64)
Consult /var/lib/dkms/kvmfr/0.0.8/build/make.log for more information.
==> WARNING: `dkms install --no-depmod kvmfr/0.0.8 -k 6.4.0-rc1-1-mainline' exited 10
```

`/var/lib/dkms/kvmfr/0.0.8/build/make.log`

```log
   1   │ DKMS make.log for kvmfr-0.0.8 for kernel 6.4.0-rc1-1-mainline (x86_64)
   2   │ Wed May 10 08:32:48 PM EEST 2023
   3   │ make -C /usr/lib/modules/6.4.0-rc1-1-mainline/build M=/var/lib/dkms/kvmfr/0.0.8/build modules
   4   │   CC [M]  /var/lib/dkms/kvmfr/0.0.8/build/kvmfr.o
   5   │ In file included from ./include/linux/linkage.h:7,
   6   │                  from ./arch/x86/include/asm/cache.h:5,
   7   │                  from ./include/linux/cache.h:6,
   8   │                  from ./arch/x86/include/asm/current.h:9,
   9   │                  from ./include/linux/sched.h:12,
  10   │                  from ./include/linux/ratelimit.h:6,
  11   │                  from ./include/linux/dev_printk.h:16,
  12   │                  from ./include/linux/device.h:15,
  13   │                  from /var/lib/dkms/kvmfr/0.0.8/build/kvmfr.c:24:
  14   │ /var/lib/dkms/kvmfr/0.0.8/build/kvmfr.c: In function ‘kvmfr_module_init’:
  15   │ ./include/linux/export.h:27:22: error: passing argument 1 of ‘class_create’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  16   │    27 | #define THIS_MODULE (&__this_module)
  17   │       |                     ~^~~~~~~~~~~~~~~
  18   │       |                      |
  19   │       |                      struct module *
  20   │ /var/lib/dkms/kvmfr/0.0.8/build/kvmfr.c:542:32: note: in expansion of macro ‘THIS_MODULE’
  21   │   542 |   kvmfr->pClass = class_create(THIS_MODULE, KVMFR_DEV_NAME);
  22   │       |                                ^~~~~~~~~~~
  23   │ In file included from ./include/linux/device.h:31:
  24   │ ./include/linux/device/class.h:229:54: note: expected ‘const char *’ but argument is of type ‘struct module *’
  25   │   229 | struct class * __must_check class_create(const char *name);
  26   │       |                                          ~~~~~~~~~~~~^~~~
  27   │ /var/lib/dkms/kvmfr/0.0.8/build/kvmfr.c:542:19: error: too many arguments to function ‘class_create’
  28   │   542 |   kvmfr->pClass = class_create(THIS_MODULE, KVMFR_DEV_NAME);
  29   │       |                   ^~~~~~~~~~~~
  30   │ ./include/linux/device/class.h:229:29: note: declared here
  31   │   229 | struct class * __must_check class_create(const char *name);
  32   │       |                             ^~~~~~~~~~~~
  33   │ cc1: some warnings being treated as errors
  34   │ make[2]: *** [scripts/Makefile.build:252: /var/lib/dkms/kvmfr/0.0.8/build/kvmfr.o] Error 1
  35   │ make[1]: *** [Makefile:2026: /var/lib/dkms/kvmfr/0.0.8/build] Error 2
  36   │ make: *** [Makefile:7: all] Error 2
```

### PR DESCRIPTION
**Pull request by esibun**
Remove second parameter from class_create since Linux >= 6.4 uses data from struct instead supplied from previous calls.  Draft PR until I can get this tested properly.

### CODE REVIEW

**Comment by esibun** [comment]
Keeping as a draft until 6.4 stable per bug discussion.
