### ISSUE TITLE
kvmfr module build problem on kernel 6.13

### ISSUE THREAD

**Issue by Psychodelta** [gnif/LookingGlass#1155]
[The parameter of MODULE_IMPORT_NS has been changed from constants to string literal: https://github.com/torvalds/linux/commit/cdd30ebb1b9f36159d66f088b61aee264e649d7a.](https://github.com/torvalds/linux/commit/cdd30ebb1b9f36159d66f088b61aee264e649d7a)

dkms install kvmfr/0.0.10
(same error goes for b6 kvmfr/0.0.8)
```
Sign command: /usr/lib/modules/6.13.0-1-cachyos-bore/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
Creating symlink /var/lib/dkms/kvmfr/0.0.10/source -> /usr/src/kvmfr-0.0.10

Cleaning build area... done.
Building module(s)...(bad exit status: 2)
Failed command:
make -j20 KERNELRELEASE=6.13.0-1-cachyos-bore KDIR=/usr/lib/modules/6.13.0-1-cachyos-bore/build

Error! Bad return status for module build on kernel: 6.13.0-1-cachyos-bore (x86_64)
Consult /var/lib/dkms/kvmfr/0.0.10/build/make.log for more information.
```

/var/lib/dkms/kvmfr/0.0.10/build/make.log

```
DKMS make.log for kvmfr/0.0.10 for kernel 6.13.0-1-cachyos-bore (x86_64)
do 23 jan 2025  6:04:19 CET
make -C /usr/lib/modules/6.13.0-1-cachyos-bore/build M=/var/lib/dkms/kvmfr/0.0.10/build modules
make[1]: Entering directory '/usr/lib/modules/6.13.0-1-cachyos-bore/build'
make[2]: Entering directory '/var/lib/dkms/kvmfr/0.0.10/build'
  CC [M]  kvmfr.o
In file included from /usr/lib/modules/6.13.0-1-cachyos-bore/build/include/linux/module.h:22,
                 from /usr/lib/modules/6.13.0-1-cachyos-bore/build/include/linux/device/driver.h:21,
                 from /usr/lib/modules/6.13.0-1-cachyos-bore/build/include/linux/device.h:32,
                 from kvmfr.c:24:
kvmfr.c:655:18: error: expected ‘,’ or ‘;’ before ‘DMA_BUF’
  655 | MODULE_IMPORT_NS(DMA_BUF);
      |                  ^~~~~~~
/usr/lib/modules/6.13.0-1-cachyos-bore/build/include/linux/moduleparam.h:26:61: note: in definition of macro ‘__MODULE_INFO’
   26 |                 = __MODULE_INFO_PREFIX __stringify(tag) "=" info
      |                                                             ^~~~
/usr/lib/modules/6.13.0-1-cachyos-bore/build/include/linux/module.h:299:33: note: in expansion of macro ‘MODULE_INFO’
  299 | #define MODULE_IMPORT_NS(ns)    MODULE_INFO(import_ns, ns)
      |                                 ^~~~~~~~~~~
kvmfr.c:655:1: note: in expansion of macro ‘MODULE_IMPORT_NS’
  655 | MODULE_IMPORT_NS(DMA_BUF);
      | ^~~~~~~~~~~~~~~~
make[4]: *** [/usr/lib/modules/6.13.0-1-cachyos-bore/build/scripts/Makefile.build:194: kvmfr.o] Error 1
make[3]: *** [/usr/lib/modules/6.13.0-1-cachyos-bore/build/Makefile:1997: .] Error 2
make[2]: *** [/usr/lib/modules/6.13.0-1-cachyos-bore/build/Makefile:251: __sub-make] Error 2
make[2]: Leaving directory '/var/lib/dkms/kvmfr/0.0.10/build'
make[1]: *** [Makefile:251: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.13.0-1-cachyos-bore/build'
make: *** [Makefile:7: all] Error 2
```

**Comment by gnif** [comment]
There is already a PR for this:
https://github.com/gnif/LookingGlass/pull/1154

**Comment by ticpu** [comment]
@gnif any reason why this is closed as completed but #1149 isn't merged?

**Comment by gnif** [comment]
There is no need to create a issue for something that already has a PR and is planned to be merged.
The delay on merging is due a problem with the automated build server and signing certs.
