### ISSUE TITLE
Compile issue in function `ivshmem_wait_irq`

### ISSUE THREAD

**Issue by Misairu-G** [gnif/LookingGlass#5]
```
gcc -c -g -O3 -std=gnu99 -march=native -Wall -Werror -I./ -I../common -DDEBUG -ffast-math -fdata-sections -ffunction-sections -D_REENTRANT -I/usr/include/SDL2 -I/usr/include/libdrm -I/usr/include/freetype2 -I/usr/include/spice-1 -DBUILD_VERSION='"a3-2-g973ad5e2b0-dirty"' -o .build/main.o main.c
gcc -c -g -O3 -std=gnu99 -march=native -Wall -Werror -I./ -I../common -DDEBUG -ffast-math -fdata-sections -ffunction-sections -D_REENTRANT -I/usr/include/SDL2 -I/usr/include/libdrm -I/usr/include/freetype2 -I/usr/include/spice-1 -DBUILD_VERSION='"a3-2-g973ad5e2b0-dirty"' -o .build/spice/spice.o spice/spice.c
gcc -c -g -O3 -std=gnu99 -march=native -Wall -Werror -I./ -I../common -DDEBUG -ffast-math -fdata-sections -ffunction-sections -D_REENTRANT -I/usr/include/SDL2 -I/usr/include/libdrm -I/usr/include/freetype2 -I/usr/include/spice-1 -DBUILD_VERSION='"a3-2-g973ad5e2b0-dirty"' -o .build/ivshmem/ivshmem.o ivshmem/ivshmem.c
ivshmem/ivshmem.c: In function ‘ivshmem_wait_irq’:
ivshmem/ivshmem.c:514:7: error: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Werror=unused-result]
       read(fd, &kick, sizeof(kick));
       ^
cc1: all warnings being treated as errors
Makefile:28: recipe for target '.build/ivshmem/ivshmem.o' failed
make: *** [.build/ivshmem/ivshmem.o] Error 1
```

Removing the `-Werror` flag can make it work. And the client work without any problem so far. No sure this warning will have any impact in the future.

Compile with gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
