### PR TITLE
[module] fix incompatibility with kernel >6.13.0

### PR DESCRIPTION
**Pull request by Letsric**
Currently, the module compiles on kernel 6.12.15 and lower

```bash
KDIR=/home/eric/Dokumente/linux/linux-6.12.15 make
```

```
make -C /home/eric/Dokumente/linux/linux-6.12.15 M=/home/eric/Dokumente/gpu-passthrough/git/LookingGlass/module modules
make[1]: Entering directory '/home/eric/Dokumente/linux/linux-6.12.15'
  CC [M]  /home/eric/Dokumente/gpu-passthrough/git/LookingGlass/module/kvmfr.o
  MODPOST /home/eric/Dokumente/gpu-passthrough/git/LookingGlass/module/Module.symvers
  CC [M]  /home/eric/Dokumente/gpu-passthrough/git/LookingGlass/module/kvmfr.mod.o
  CC [M]  /home/eric/Dokumente/gpu-passthrough/git/LookingGlass/module/.module-common.o
  LD [M]  /home/eric/Dokumente/gpu-passthrough/git/LookingGlass/module/kvmfr.ko
make[1]: Leaving directory '/home/eric/Dokumente/linux/linux-6.12.15'
```

but not on 6.13.x

```bash
KDIR=/home/eric/Dokumente/linux/linux-6.13 make
```

```
make -C /home/eric/Dokumente/linux/linux-6.13 M=/home/eric/Dokumente/gpu-passthrough/git/LookingGlass/module modules
make[1]: Entering directory '/home/eric/Dokumente/linux/linux-6.13'
make[2]: Entering directory '/home/eric/Dokumente/gpu-passthrough/git/LookingGlass/module'
  CC [M]  kvmfr.o
In file included from /home/eric/Dokumente/linux/linux-6.13/include/linux/module.h:22,
                 from /home/eric/Dokumente/linux/linux-6.13/include/linux/device/driver.h:21,
                 from /home/eric/Dokumente/linux/linux-6.13/include/linux/device.h:32,
                 from kvmfr.c:24:
kvmfr.c:659:18: error: expected ',' or ';' before 'DMA_BUF'
  659 | MODULE_IMPORT_NS(DMA_BUF);
      |                  ^~~~~~~
/home/eric/Dokumente/linux/linux-6.13/include/linux/moduleparam.h:26:61: note: in definition of macro '__MODULE_INFO'
   26 |                 = __MODULE_INFO_PREFIX __stringify(tag) "=" info
      |                                                             ^~~~
/home/eric/Dokumente/linux/linux-6.13/include/linux/module.h:299:33: note: in expansion of macro 'MODULE_INFO'
  299 | #define MODULE_IMPORT_NS(ns)    MODULE_INFO(import_ns, ns)
      |                                 ^~~~~~~~~~~
kvmfr.c:659:1: note: in expansion of macro 'MODULE_IMPORT_NS'
  659 | MODULE_IMPORT_NS(DMA_BUF);
      | ^~~~~~~~~~~~~~~~
make[4]: *** [/home/eric/Dokumente/linux/linux-6.13/scripts/Makefile.build:194: kvmfr.o] Error 1
make[3]: *** [/home/eric/Dokumente/linux/linux-6.13/Makefile:1989: .] Error 2
make[2]: *** [/home/eric/Dokumente/linux/linux-6.13/Makefile:251: __sub-make] Error 2
make[2]: Leaving directory '/home/eric/Dokumente/gpu-passthrough/git/LookingGlass/module'
make[1]: *** [Makefile:251: __sub-make] Error 2
make[1]: Leaving directory '/home/eric/Dokumente/linux/linux-6.13'
make: *** [Makefile:7: all] Error 2
```

due to a small change in namespace importing. (Namespace now needs to be in quotes) See [6.12 docs](https://www.kernel.org/doc/html/v6.12/core-api/symbol-namespaces.html#how-to-use-symbols-exported-in-namespaces) vs [6.13 docs](https://www.kernel.org/doc/html/v6.13/core-api/symbol-namespaces.html#how-to-use-symbols-exported-in-namespaces).

This PR fixes this issue:

```bash
KDIR=/home/eric/Dokumente/linux/linux-6.12.15 make
```

make -C /home/eric/Dokumente/linux/linux-6.12.15 M=/home/eric/Dokumente/gpu-passthrough/git/LookingGlass/module modules
make[1]: Entering directory '/home/eric/Dokumente/linux/linux-6.12.15'
  CC [M]  /home/eric/Dokumente/gpu-passthrough/git/LookingGlass/module/kvmfr.o
  MODPOST /home/eric/Dokumente/gpu-passthrough/git/LookingGlass/module/Module.symvers
  CC [M]  /home/eric/Dokumente/gpu-passthrough/git/LookingGlass/module/kvmfr.mod.o
  CC [M]  /home/eric/Dokumente/gpu-passthrough/git/LookingGlass/module/.module-common.o
  LD [M]  /home/eric/Dokumente/gpu-passthrough/git/LookingGlass/module/kvmfr.ko
make[1]: Leaving directory '/home/eric/Dokumente/linux/linux-6.12.15'

```bash
KDIR=/home/eric/Dokumente/linux/linux-6.13 make
```

```
make -C /home/eric/Dokumente/linux/linux-6.13 M=/home/eric/Dokumente/gpu-passthrough/git/LookingGlass/module modules
make[1]: Entering directory '/home/eric/Dokumente/linux/linux-6.13'
make[2]: Entering directory '/home/eric/Dokumente/gpu-passthrough/git/LookingGlass/module'
  CC [M]  kvmfr.o
  MODPOST Module.symvers
  CC [M]  kvmfr.mod.o
  CC [M]  .module-common.o
  LD [M]  kvmfr.ko
make[2]: Leaving directory '/home/eric/Dokumente/gpu-passthrough/git/LookingGlass/module'
make[1]: Leaving directory '/home/eric/Dokumente/linux/linux-6.13'
```

most importantly, it makes the module compilable for the latest stable kernel

```bash
KDIR=/home/eric/Dokumente/linux/linux-6.13.3 make
```

```
make -C /home/eric/Dokumente/linux/linux-6.13.3 M=/home/eric/Dokumente/gpu-passthrough/git/LookingGlass/module modules
make[1]: Entering directory '/home/eric/Dokumente/linux/linux-6.13.3'
make[2]: Entering directory '/home/eric/Dokumente/gpu-passthrough/git/LookingGlass/module'
  CC [M]  kvmfr.o
  MODPOST Module.symvers
  CC [M]  kvmfr.mod.o
  CC [M]  .module-common.o
  LD [M]  kvmfr.ko
make[2]: Leaving directory '/home/eric/Dokumente/gpu-passthrough/git/LookingGlass/module'
make[1]: Leaving directory '/home/eric/Dokumente/linux/linux-6.13.3'
```

### CODE REVIEW

**Comment by Letsric** [comment]
sorry, just saw someone already created a PR for this (#1149). I'm stupid :D
