### ISSUE TITLE
Failure to build client B1-rc6

### ISSUE THREAD

**Issue by 8BallBomBom** [gnif/LookingGlass#173]
Seem to be getting an error trying to build using Kubuntu 19.04
Here is the error, also everything as per the compile guide is installed.
```
Scanning dependencies of target looking-glass-client
[ 89%] Building C object CMakeFiles/looking-glass-client.dir/src/main.c.o
In file included from /home/johnathon/Downloads/LookingGlass-B1-rc6/client/src/main.c:20:
/home/johnathon/Downloads/LookingGlass-B1-rc6/client/src/main.h:27:10: fatal error: spice/spice.h: No such file or directory
 #include "spice/spice.h"
          ^~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/looking-glass-client.dir/build.make:63: CMakeFiles/looking-glass-client.dir/src/main.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:82: CMakeFiles/looking-glass-client.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```
The cmake output log.
```
The system is: Linux - 5.0.0-16-generic - x86_64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: /usr/bin/cc 
Build flags: 
Id flags:  

The output was:
0

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.out"

The C compiler identification is GNU, found in "/home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/3.13.4/CompilerIdC/a.out"

Determining if the C compiler works passed with the following output:
Change Dir: /home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_b674c/fast"
/usr/bin/make -f CMakeFiles/cmTC_b674c.dir/build.make CMakeFiles/cmTC_b674c.dir/build
make[1]: Entering directory '/home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_b674c.dir/testCCompiler.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_b674c.dir/testCCompiler.c.o   -c /home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/CMakeTmp/testCCompiler.c
Linking C executable cmTC_b674c
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_b674c.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic CMakeFiles/cmTC_b674c.dir/testCCompiler.c.o  -o cmTC_b674c 
make[1]: Leaving directory '/home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/CMakeTmp'

Detecting C compiler ABI info compiled with the following output:
Change Dir: /home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_e9af9/fast"
/usr/bin/make -f CMakeFiles/cmTC_e9af9.dir/build.make CMakeFiles/cmTC_e9af9.dir/build
make[1]: Entering directory '/home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_e9af9.dir/CMakeCCompilerABI.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_e9af9.dir/CMakeCCompilerABI.c.o   -c /usr/share/cmake-3.13/Modules/CMakeCCompilerABI.c
Linking C executable cmTC_e9af9
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_e9af9.dir/link.txt --verbose=1
/usr/bin/cc     -v -rdynamic CMakeFiles/cmTC_e9af9.dir/CMakeCCompilerABI.c.o  -o cmTC_e9af9 
Using built-in specs.
COLLECT_GCC=/usr/bin/cc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 8.3.0-6ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1) 
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/8/:/usr/lib/gcc/x86_64-linux-gnu/8/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/8/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/8/:/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/8/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-v' '-rdynamic' '-o' 'cmTC_e9af9' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/8/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/8/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper -plugin-opt=-fresolution=/tmp/ccV6x8Az.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -export-dynamic -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -z now -z relro -o cmTC_e9af9 /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/8/crtbeginS.o -L/usr/lib/gcc/x86_64-linux-gnu/8 -L/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/8/../../.. CMakeFiles/cmTC_e9af9.dir/CMakeCCompilerABI.c.o -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-linux-gnu/8/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/crtn.o
COLLECT_GCC_OPTIONS='-v' '-rdynamic' '-o' 'cmTC_e9af9' '-mtune=generic' '-march=x86-64'
make[1]: Leaving directory '/home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/CMakeTmp'

Parsed C implicit link information from above output:
  link line regex: [^( *|.*[/\])(ld|CMAKE_LINK_STARTFILE-NOTFOUND|([^/\]+-)?ld|collect2)[^/\]*( |$)]
  ignore line: [Change Dir: /home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/CMakeTmp]
  ignore line: []
  ignore line: [Run Build Command:"/usr/bin/make" "cmTC_e9af9/fast"]
  ignore line: [/usr/bin/make -f CMakeFiles/cmTC_e9af9.dir/build.make CMakeFiles/cmTC_e9af9.dir/build]
  ignore line: [make[1]: Entering directory '/home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/CMakeTmp']
  ignore line: [Building C object CMakeFiles/cmTC_e9af9.dir/CMakeCCompilerABI.c.o]
  ignore line: [/usr/bin/cc    -o CMakeFiles/cmTC_e9af9.dir/CMakeCCompilerABI.c.o   -c /usr/share/cmake-3.13/Modules/CMakeCCompilerABI.c]
  ignore line: [Linking C executable cmTC_e9af9]
  ignore line: [/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_e9af9.dir/link.txt --verbose=1]
  ignore line: [/usr/bin/cc     -v -rdynamic CMakeFiles/cmTC_e9af9.dir/CMakeCCompilerABI.c.o  -o cmTC_e9af9 ]
  ignore line: [Using built-in specs.]
  ignore line: [COLLECT_GCC=/usr/bin/cc]
  ignore line: [COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper]
  ignore line: [OFFLOAD_TARGET_NAMES=nvptx-none]
  ignore line: [OFFLOAD_TARGET_DEFAULT=1]
  ignore line: [Target: x86_64-linux-gnu]
  ignore line: [Configured with: ../src/configure -v --with-pkgversion='Ubuntu 8.3.0-6ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu]
  ignore line: [Thread model: posix]
  ignore line: [gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1) ]
  ignore line: [COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/8/:/usr/lib/gcc/x86_64-linux-gnu/8/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/8/:/usr/lib/gcc/x86_64-linux-gnu/]
  ignore line: [LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/8/:/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/../lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/8/../../../:/lib/:/usr/lib/]
  ignore line: [COLLECT_GCC_OPTIONS='-v' '-rdynamic' '-o' 'cmTC_e9af9' '-mtune=generic' '-march=x86-64']
  link line: [ /usr/lib/gcc/x86_64-linux-gnu/8/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/8/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper -plugin-opt=-fresolution=/tmp/ccV6x8Az.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -export-dynamic -dynamic-linker /lib64/ld-linux-x86-64.so.2 -pie -z now -z relro -o cmTC_e9af9 /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/Scrt1.o /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/8/crtbeginS.o -L/usr/lib/gcc/x86_64-linux-gnu/8 -L/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/8/../../.. CMakeFiles/cmTC_e9af9.dir/CMakeCCompilerABI.c.o -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-linux-gnu/8/crtendS.o /usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/crtn.o]
    arg [/usr/lib/gcc/x86_64-linux-gnu/8/collect2] ==> ignore
    arg [-plugin] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/8/liblto_plugin.so] ==> ignore
    arg [-plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper] ==> ignore
    arg [-plugin-opt=-fresolution=/tmp/ccV6x8Az.res] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc_s] ==> ignore
    arg [-plugin-opt=-pass-through=-lc] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc] ==> ignore
    arg [-plugin-opt=-pass-through=-lgcc_s] ==> ignore
    arg [--build-id] ==> ignore
    arg [--eh-frame-hdr] ==> ignore
    arg [-m] ==> ignore
    arg [elf_x86_64] ==> ignore
    arg [--hash-style=gnu] ==> ignore
    arg [--as-needed] ==> ignore
    arg [-export-dynamic] ==> ignore
    arg [-dynamic-linker] ==> ignore
    arg [/lib64/ld-linux-x86-64.so.2] ==> ignore
    arg [-pie] ==> ignore
    arg [-znow] ==> ignore
    arg [-zrelro] ==> ignore
    arg [-o] ==> ignore
    arg [cmTC_e9af9] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/Scrt1.o] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/crti.o] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/8/crtbeginS.o] ==> ignore
    arg [-L/usr/lib/gcc/x86_64-linux-gnu/8] ==> dir [/usr/lib/gcc/x86_64-linux-gnu/8]
    arg [-L/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu] ==> dir [/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu]
    arg [-L/usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib] ==> dir [/usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib]
    arg [-L/lib/x86_64-linux-gnu] ==> dir [/lib/x86_64-linux-gnu]
    arg [-L/lib/../lib] ==> dir [/lib/../lib]
    arg [-L/usr/lib/x86_64-linux-gnu] ==> dir [/usr/lib/x86_64-linux-gnu]
    arg [-L/usr/lib/../lib] ==> dir [/usr/lib/../lib]
    arg [-L/usr/lib/gcc/x86_64-linux-gnu/8/../../..] ==> dir [/usr/lib/gcc/x86_64-linux-gnu/8/../../..]
    arg [CMakeFiles/cmTC_e9af9.dir/CMakeCCompilerABI.c.o] ==> ignore
    arg [-lgcc] ==> lib [gcc]
    arg [--push-state] ==> ignore
    arg [--as-needed] ==> ignore
    arg [-lgcc_s] ==> lib [gcc_s]
    arg [--pop-state] ==> ignore
    arg [-lc] ==> lib [c]
    arg [-lgcc] ==> lib [gcc]
    arg [--push-state] ==> ignore
    arg [--as-needed] ==> ignore
    arg [-lgcc_s] ==> lib [gcc_s]
    arg [--pop-state] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/8/crtendS.o] ==> ignore
    arg [/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu/crtn.o] ==> ignore
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/8] ==> [/usr/lib/gcc/x86_64-linux-gnu/8]
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/8/../../../x86_64-linux-gnu] ==> [/usr/lib/x86_64-linux-gnu]
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/8/../../../../lib] ==> [/usr/lib]
  collapse library dir [/lib/x86_64-linux-gnu] ==> [/lib/x86_64-linux-gnu]
  collapse library dir [/lib/../lib] ==> [/lib]
  collapse library dir [/usr/lib/x86_64-linux-gnu] ==> [/usr/lib/x86_64-linux-gnu]
  collapse library dir [/usr/lib/../lib] ==> [/usr/lib]
  collapse library dir [/usr/lib/gcc/x86_64-linux-gnu/8/../../..] ==> [/usr/lib]
  implicit libs: [gcc;gcc_s;c;gcc;gcc_s]
  implicit dirs: [/usr/lib/gcc/x86_64-linux-gnu/8;/usr/lib/x86_64-linux-gnu;/usr/lib;/lib/x86_64-linux-gnu;/lib]
  implicit fwks: []

Detecting C [-std=c11] compiler features compiled with the following output:
Change Dir: /home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_963f7/fast"
/usr/bin/make -f CMakeFiles/cmTC_963f7.dir/build.make CMakeFiles/cmTC_963f7.dir/build
make[1]: Entering directory '/home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_963f7.dir/feature_tests.c.o
/usr/bin/cc   -std=c11 -o CMakeFiles/cmTC_963f7.dir/feature_tests.c.o   -c /home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/feature_tests.c
Linking C executable cmTC_963f7
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_963f7.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic CMakeFiles/cmTC_963f7.dir/feature_tests.c.o  -o cmTC_963f7 
make[1]: Leaving directory '/home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/CMakeTmp'


    Feature record: C_FEATURE:1c_function_prototypes
    Feature record: C_FEATURE:1c_restrict
    Feature record: C_FEATURE:1c_static_assert
    Feature record: C_FEATURE:1c_variadic_macros


Detecting C [-std=c99] compiler features compiled with the following output:
Change Dir: /home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_6dc5d/fast"
/usr/bin/make -f CMakeFiles/cmTC_6dc5d.dir/build.make CMakeFiles/cmTC_6dc5d.dir/build
make[1]: Entering directory '/home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_6dc5d.dir/feature_tests.c.o
/usr/bin/cc   -std=c99 -o CMakeFiles/cmTC_6dc5d.dir/feature_tests.c.o   -c /home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/feature_tests.c
Linking C executable cmTC_6dc5d
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_6dc5d.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic CMakeFiles/cmTC_6dc5d.dir/feature_tests.c.o  -o cmTC_6dc5d 
make[1]: Leaving directory '/home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/CMakeTmp'


    Feature record: C_FEATURE:1c_function_prototypes
    Feature record: C_FEATURE:1c_restrict
    Feature record: C_FEATURE:0c_static_assert
    Feature record: C_FEATURE:1c_variadic_macros


Detecting C [-std=c90] compiler features compiled with the following output:
Change Dir: /home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_ba97c/fast"
/usr/bin/make -f CMakeFiles/cmTC_ba97c.dir/build.make CMakeFiles/cmTC_ba97c.dir/build
make[1]: Entering directory '/home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_ba97c.dir/feature_tests.c.o
/usr/bin/cc   -std=c90 -o CMakeFiles/cmTC_ba97c.dir/feature_tests.c.o   -c /home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/feature_tests.c
Linking C executable cmTC_ba97c
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_ba97c.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic CMakeFiles/cmTC_ba97c.dir/feature_tests.c.o  -o cmTC_ba97c 
make[1]: Leaving directory '/home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/CMakeTmp'


    Feature record: C_FEATURE:1c_function_prototypes
    Feature record: C_FEATURE:0c_restrict
    Feature record: C_FEATURE:0c_static_assert
    Feature record: C_FEATURE:0c_variadic_macros
Performing C SOURCE FILE Test COMPILER_SUPPORTS_MARCH_NATIVE succeeded with the following output:
Change Dir: /home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_c80bd/fast"
/usr/bin/make -f CMakeFiles/cmTC_c80bd.dir/build.make CMakeFiles/cmTC_c80bd.dir/build
make[1]: Entering directory '/home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_c80bd.dir/src.c.o
/usr/bin/cc   -DCOMPILER_SUPPORTS_MARCH_NATIVE   -march=native -o CMakeFiles/cmTC_c80bd.dir/src.c.o   -c /home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_c80bd
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_c80bd.dir/link.txt --verbose=1
/usr/bin/cc  -DCOMPILER_SUPPORTS_MARCH_NATIVE    -rdynamic CMakeFiles/cmTC_c80bd.dir/src.c.o  -o cmTC_c80bd 
make[1]: Leaving directory '/home/johnathon/Downloads/LookingGlass-B1-rc6/client/build/CMakeFiles/CMakeTmp'

Source file was:
int main(void) { return 0; }
```

**Comment by gnif** [comment]
Not a bug, make sure you have the spice protocol headers installed. If you continue to have trouble please ask for help on the L1Tech forums.

Git wont allow me to close issues, seems they have a server fault. Consider this closed in the meantime please.

**Comment by 8BallBomBom** [comment]
Sadly doesn't seem to make any difference, still can't compile even the latest client.
I have purged/reinstalled everything required.

```
cmake is already the newest version (3.13.4-1).
fonts-freefont-ttf is already the newest version (20120503-9).
libfontconfig1-dev is already the newest version (2.13.1-2ubuntu2).
libspice-protocol-dev is already the newest version (0.12.14-1).
libx11-dev is already the newest version (2:1.6.7-1).
nettle-dev is already the newest version (3.4.1-1).
libconfig-dev is already the newest version (1.5-0.4).
libsdl2-dev is already the newest version (2.0.9+dfsg1-1ubuntu1).
libsdl2-ttf-dev is already the newest version (2.0.15+dfsg1-1).
```

**Comment by 8BallBomBom** [comment]
@gnif I've tried another clean install of Ubuntu 19.04 and it would appear the same issue appears.
Did the packages change for libspice? not exactly sure but can't build.
