### ISSUE TITLE
Host module fails to compile on kernel >= 5.9

### ISSUE THREAD

**Issue by WilliamImm** [gnif/LookingGlass#314]
The host module for LookingGlass version B2 failed compilation w/ kernel version 5.9.1:

```log
DKMS make.log for looking-glass-B2 for kernel 5.9.1-arch1-1 (x86_64)
Sun Oct 18 01:32:20 AM CDT 2020
make -C /usr/lib/modules/5.9.1-arch1-1/build M=/var/lib/dkms/looking-glass/B2/build modules
make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
make[1]: Entering directory '/usr/lib/modules/5.9.1-arch1-1/build'
  CC [M]  /var/lib/dkms/looking-glass/B2/build/kvmfr.o
/var/lib/dkms/looking-glass/B2/build/kvmfr.c: In function ‘kvmfr_pci_probe’:
/var/lib/dkms/looking-glass/B2/build/kvmfr.c:308:27: error: ‘MEMORY_DEVICE_DEVDAX’ undeclared (first use in this function); did you mean ‘MEMORY_DEVICE_FS_DAX’?
  308 |   kdev->pgmap.type      = MEMORY_DEVICE_DEVDAX;
      |                           ^~~~~~~~~~~~~~~~~~~~
      |                           MEMORY_DEVICE_FS_DAX
/var/lib/dkms/looking-glass/B2/build/kvmfr.c:308:27: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [scripts/Makefile.build:283: /var/lib/dkms/looking-glass/B2/build/kvmfr.o] Error 1
make[1]: *** [Makefile:1784: /var/lib/dkms/looking-glass/B2/build] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.9.1-arch1-1/build'
make: *** [Makefile:7: all] Error 2
```

Using an Arch Linux system. Premliary research points to [a recent kernel patch that renamed the offending device type to MEMORY_DEVICE_GENERIC](https://patchwork.kernel.org/project/linux-nvdimm/patch/20200811094447.31208-2-roger.pau@citrix.com/), which was applied in kernel version 5.9.
