### ISSUE TITLE
[c-host] For Linux on Linux build fails due to missing timer function implementations

### ISSUE THREAD

**Issue by Omar007** [gnif/LookingGlass#276]
Building the c-host application for Linux on Linux seems to have started failing since commit fdb9a9cca854df1152e9ec0fbfbe7f92d8ecc698
It looks like there might be a time.c implementation missing for the Linux platform.

```
/usr/bin/ld: CMakeFiles/looking-glass-host.dir/src/app.c.o: in function `startThreads':
app.c:(.text.startThreads+0x34): undefined reference to `lgCreateTimer'
/usr/bin/ld: CMakeFiles/looking-glass-host.dir/src/app.c.o: in function `stopThreads':
app.c:(.text.stopThreads+0x61): undefined reference to `lgTimerDestroy'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/looking-glass-host.dir/build.make:113: looking-glass-host] Error 1
make[1]: *** [CMakeFiles/Makefile2:258: CMakeFiles/looking-glass-host.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```

**Comment by mafrasi2** [comment]
I've implemented linux timers [here](https://github.com/mafrasi2/LookingGlass/tree/linux_host). There were a few other compilation issues, which I also fixed.

I still can't get it to work since `egl_cursor_set_state()` segfaults on the client and when I remove the segfaulting code, the window stays blank. Maybe that's just due to my own setup though.

**Comment by gnif** [comment]
@mafrasi2 would you be kind enough to make a PR for the timer code? It would be awesome to get this into the project.

**Comment by mafrasi2** [comment]
@gnif Absolutely, I was planning to do that anyways. Just wasn't sure whether to make one before I got it working completely :)

**Comment by gnif** [comment]
`egl_cursor_set_state` is unrelated, this is only called on windows resize when using the egl renderer, there nothing there that uses the timers.

**Comment by gnif** [comment]
Closing as per #292
