### ISSUE TITLE
Cannot build kvmfr module on Arch Linux.

### ISSUE THREAD

**Issue by JunaidQrysh** [gnif/LookingGlass#1134]
I downloaded the B7-rc1 zip, running sudo dkms install "." produces this-
Sign command: /usr/lib/modules/6.10.6-arch1-1/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
Creating symlink /var/lib/dkms/kvmfr/0.0.9/source -> /usr/src/kvmfr-0.0.9

Building module:
Cleaning build area...
make -j16 KERNELRELEASE=6.10.6-arch1-1 KDIR=/usr/lib/modules/6.10.6-arch1-1/build...(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.10.6-arch1-1 (x86_64)
Consult /var/lib/dkms/kvmfr/0.0.9/build/make.log for more information.

And here is **/var/lib/dkms/kvmfr/0.0.0/build/make.log-**

DKMS make.log for kvmfr-0.0.9 for kernel 6.10.6-arch1-1 (x86_64)
Mon Aug 26 01:59:32 PM IST 2024
make -C /usr/lib/modules/6.10.6-arch1-1/build M=/var/lib/dkms/kvmfr/0.0.9/build modules
make[1]: Entering directory '/usr/lib/modules/6.10.6-arch1-1/build'
  CC [M]  /var/lib/dkms/kvmfr/0.0.9/build/kvmfr.o
/var/lib/dkms/kvmfr/0.0.9/build/kvmfr.c: In function ‘mmap_kvmfrbuf’:
/var/lib/dkms/kvmfr/0.0.9/build/kvmfr.c:167:14: error: implicit declaration of function ‘remap_vmalloc_range’; did you mean ‘ida_alloc_range’? [-Wimplicit-function-declaration]
  167 |       return remap_vmalloc_range(vma, kbuf->kdev->addr + kbuf->offset,
      |              ^~~~~~~~~~~~~~~~~~~
      |              ida_alloc_range
/var/lib/dkms/kvmfr/0.0.9/build/kvmfr.c: In function ‘create_static_device_unlocked’:
/var/lib/dkms/kvmfr/0.0.9/build/kvmfr.c:508:16: error: implicit declaration of function ‘vmalloc_user’ [-Wimplicit-function-declaration]
  508 |   kdev->addr = vmalloc_user(kdev->size);
      |                ^~~~~~~~~~~~
/var/lib/dkms/kvmfr/0.0.9/build/kvmfr.c:508:14: error: assignment to ‘void *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  508 |   kdev->addr = vmalloc_user(kdev->size);
      |              ^
/var/lib/dkms/kvmfr/0.0.9/build/kvmfr.c:533:3: error: implicit declaration of function ‘vfree’; did you mean ‘kvfree’? [-Wimplicit-function-declaration]
  533 |   vfree(kdev->addr);
      |   ^~~~~
      |   kvfree
make[3]: *** [scripts/Makefile.build:244: /var/lib/dkms/kvmfr/0.0.9/build/kvmfr.o] Error 1
make[2]: *** [/usr/lib/modules/6.10.6-arch1-1/build/Makefile:1934: /var/lib/dkms/kvmfr/0.0.9/build] Error 2
make[1]: *** [Makefile:240: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.10.6-arch1-1/build'
make: *** [Makefile:7: all] Error 2

**Comment by gnif** [comment]
Already fixed in 7305ce36af211220419eeab302ff28793d515df2
Closing as invalid
