### PR TITLE
[module] fix build with kernel >= 6.13

### PR DESCRIPTION
**Pull request by zeule**
Account for kernel commit cdd30ebb1b9f36159d66f088b61aee264e649d7a: module: Convert symbol namespace to string literal

### CODE REVIEW

**Comment by Svenum** [comment]
I got the following build error:
```bash
       > make[2]: Entering directory '/build/source/module'
       >   CC [M]  kvmfr.o
       > In file included from /nix/store/6b9j17qfxdvyh9kmi9fjgh6zg0ix8if5-linux-6.13-dev/lib/modules/6.13.0/source/include/linux/module.h:22,
       >                  from /nix/store/6b9j17qfxdvyh9kmi9fjgh6zg0ix8if5-linux-6.13-dev/lib/modules/6.13.0/source/include/linux/device/driver.h:21,
       >                  from /nix/store/6b9j17qfxdvyh9kmi9fjgh6zg0ix8if5-linux-6.13-dev/lib/modules/6.13.0/source/include/linux/device.h:32,
       >                  from kvmfr.c:24:
       > kvmfr.c:659:18: error: expected ',' or ';' before 'DMA_BUF'
       >   659 | MODULE_IMPORT_NS(DMA_BUF);
       >       |                  ^~~~~~~
       > /nix/store/6b9j17qfxdvyh9kmi9fjgh6zg0ix8if5-linux-6.13-dev/lib/modules/6.13.0/source/include/linux/moduleparam.h:26:61: note: in definition of macro '__MODULE_INFO'
       >    26 |                 = __MODULE_INFO_PREFIX __stringify(tag) "=" info
       >       |                                                             ^~~~
       > /nix/store/6b9j17qfxdvyh9kmi9fjgh6zg0ix8if5-linux-6.13-dev/lib/modules/6.13.0/source/include/linux/module.h:299:33: note: in expansion of macro 'MODULE_INFO'
       >   299 | #define MODULE_IMPORT_NS(ns)    MODULE_INFO(import_ns, ns)
       >       |                                 ^~~~~~~~~~~
       > kvmfr.c:659:1: note: in expansion of macro 'MODULE_IMPORT_NS'
       >   659 | MODULE_IMPORT_NS(DMA_BUF);
       >       | ^~~~~~~~~~~~~~~~
       > make[4]: *** [/nix/store/6b9j17qfxdvyh9kmi9fjgh6zg0ix8if5-linux-6.13-dev/lib/modules/6.13.0/source/scripts/Makefile.build:194: kvmfr.o] Error 1
       > make[3]: *** [/nix/store/6b9j17qfxdvyh9kmi9fjgh6zg0ix8if5-linux-6.13-dev/lib/modules/6.13.0/source/Makefile:1989: .] Error 2
       > make[2]: *** [/nix/store/6b9j17qfxdvyh9kmi9fjgh6zg0ix8if5-linux-6.13-dev/lib/modules/6.13.0/source/Makefile:251: __sub-make] Error 2
       > make[2]: Leaving directory '/build/source/module'
       > make[1]: *** [/nix/store/6b9j17qfxdvyh9kmi9fjgh6zg0ix8if5-linux-6.13-dev/lib/modules/6.13.0/source/Makefile:251: __sub-make] Error 2
       > make[1]: Leaving directory '/nix/store/6b9j17qfxdvyh9kmi9fjgh6zg0ix8if5-linux-6.13-dev/lib/modules/6.13.0/build'
       > make: *** [Makefile:7: all] Error 2
```

**Comment by zeule** [comment]
> kvmfr.c:659:1: note: in expansion of macro 'MODULE_IMPORT_NS'
 >   659 | MODULE_IMPORT_NS(DMA_BUF);

With this patch the unquoted DMA_BUF is in line 661.

**Comment by Svenum** [comment]
> > kvmfr.c:659:1: note: in expansion of macro 'MODULE_IMPORT_NS'
> > 659 | MODULE_IMPORT_NS(DMA_BUF);
> 
> With this patch the unquoted DMA_BUF is in line 661.

Getting fixed here: https://github.com/gnif/LookingGlass/pull/1149

I am waiting for this PR, any news?

**Comment by zeule** [comment]
> Getting fixed here: #1149

I presume that would fail to build with kernels < 6.13

**Comment by ticpu** [comment]
> I presume that would fail to build with kernels < 6.13

Like I wrote in my PR, it still builds on at reast 6.11.

File: module/kvmfr.c [hunk 1]
```diff
@@ -655,6 +655,8 @@ MODULE_LICENSE("GPL v2");
 MODULE_AUTHOR("Geoffrey McRae <geoff@hostfission.com>");
 MODULE_AUTHOR("Guanzhong Chen <quantum2048@gmail.com>");
 MODULE_VERSION("0.0.9");
```
Comment (netboy3) [inline module/kvmfr.c:657]: You should increase The module version to 0.0.12, and make a similar change in dkms.conf. This allows dkms to sense that an updated module is needed.

**Comment by netboy3** [comment]
You should include in this PR adding yourself to the AUTHORS file. You should also consider giving credit to ticpu as they preceded you in targeting the issue.

File: module/kvmfr.c [hunk 2]
```diff
@@ -655,6 +655,8 @@ MODULE_LICENSE("GPL v2");
...
-#if LINUX_VERSION_CODE >= KERNEL_VERSION(5,16,0)
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(6,13,0)
```
Comment (ticpu) [inline module/kvmfr.c:658]: This #if is superfluous as MODULE_IMPORT_NS supports string since 5.10

Ref: https://github.com/torvalds/linux/commit/33def8498fdde180023444b08e12b72a9efed41d

Comment (zeule) [reply module/kvmfr.c:658]: Then I close this in favour of #1149.
