### ISSUE TITLE
Ubuntu 20.04 x86_64 client build error and workaround

### ISSUE THREAD

**Issue by wheelcomplex** [gnif/LookingGlass#260]
### Required information

Host CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
Host GPU: 01:00.0 VGA compatible controller: NVIDIA Corporation GP106M [GeForce GTX 1060 Mobile] (rev a1)
Guest GPU: NA
Host Kernel version:  5.4.0-18-generic #22-Ubuntu
Host QEMU version:  qemu-system-x86 1:4.2-3ubuntu4

Client Build on Ubuntu 20.04 x86_64 shows:
`[ 17%] Building C object decoders/CMakeFiles/decoders.dir/src/null.c.o
In file included from /lxvms/vscodewin/LookingGlass/client/include/interface/renderer.h:25,
                 from /lxvms/vscodewin/LookingGlass/client/include/interface/decoder.h:22,
                 from /lxvms/vscodewin/LookingGlass/client/decoders/src/null.c:20:
/usr/include/SDL2/SDL_ttf.h:34:10: fatal error: SDL.h: No such file or directory
   34 | #include "SDL.h"`

Note: /usr/include/SDL2/SDL_ttf.h comes from package libsdl2-ttf-dev

I am not sure what is the root case, but here is a patch for workaround:

`
--- a	2020-03-30 15:22:50.991561878 +1300
+++ /usr/include/SDL2/SDL_ttf.h	2020-03-30 15:12:21.551970206 +1300
@@ -31,8 +31,8 @@
 #ifndef SDL_TTF_H_
 #define SDL_TTF_H_
 
-#include "SDL.h"
-#include "begin_code.h"
+#include <SDL2/SDL.h>
+#include <SDL2/begin_code.h>
 
 /* Set up for C function definitions, even when using C++ */
 #ifdef __cplusplus
@@ -287,7 +287,7 @@
 #ifdef __cplusplus
 }
 #endif
-#include "close_code.h"
+#include <SDL2/close_code.h>
 
 #endif /* SDL_TTF_H_ */

 `

**Comment by gnif** [comment]
Not a LG bug but an issue with your distro's packaging or your local system setup.
